# CI de Nível 02 - Disparo automático em períodos definidos

# nome que vai aparecer nas opções de pipelines
name: 'Execução Agendada'

# triggers OU gatilhos de execução
# gatilho de execução manual - schedule

on:
  schedule:
    # a -> minuto
    # b -> hora
    # c -> dias do mês
    # d -> meses do ano
    # e -> dias da semana
    # crontab guru
    - cron: '0 8 * * 1'
jobs:
  # descricao do job
  e2e-tests:
    # maquina que o job vai executar
    runs-on: [ubuntu-latest]

    # passo a passo das acoes do job
    steps:
      - uses: actions/checkout@v4

      #- uses: action/setup-node@v4
      # with:
      #   node-version: lts/*

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      # passed, failed, cancelled.
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
