# CI de Nível 03 - Disparo automático sempre que outro for concluído, como deploy

# nome que vai aparecer nas opções de pipelines
name: 'Execução por Deploy'

# triggers OU gatilhos de execução
  # gatilho do exec após outro workflow - workflow_rub

on:
  workflow_run:
    workflows: ['Execução Manual']
    types:  
    - completed


jobs:

# descricao do job
    e2e-tests:

        # maquina que o job vai executar
        runs-on: [ubuntu-latest] 

        # passo a passo das acoes do job
        steps:
        
            - uses: actions/checkout@v4
            
            #- uses: action/setup-node@v4
            # with:
            #   node-version: lts/*

            - name: Instalando Yarn
              run: npm install -g yarn

            - name: Instalando dependências
              run: yarn

            - name: Instalando Playwright
              run: yarn playwright install

            - name: Testes E2E (end-to-end)
              run: yarn run e2e    
             
            # passed, failed, cancelled. 
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: relatorio-de-testes
                path: ./playwright-report