# CI de Nível 04 - Disparo dentro do fluxo de CI de desenvolvimento

# nome que vai aparecer nas opções de pipelines
name: 'Execução Integrada'

# triggers OU gatilhos de execução
# gatilho de execução manual - workflow_dispactch

on: workflow_dispatch

# inspeção
#   padronização (formatação de código)
# testes <3
#   unidade
#   e2e <3
#     buid
# deploy

jobs:
  # descricao do job
  inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Padronização de código (Lint)
        run: yarn lint

  # descricao do job
  unit:
    runs-on: ubuntu-latest
    needs: [inspection]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Testes Unidade
        run: yarn run test

  # descricao do job
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ubuntu-latest
    needs: [unit]

    # passo a passo das acoes do job
    steps:
      - uses: actions/checkout@v4

      #- uses: action/setup-node@v4
      # with:
      #   node-version: lts/*

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Subir aplicação local
        run: yarn start &

      - name: Testes E2E (end-to-end)
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000'

      # passed, failed, cancelled.
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report

  deploy:
    # maquina que o job vai executar
    runs-on: ubuntu-latest
    needs: [e2e-tests]
